UPDATE text_pair SET text1='L''interface de cette plateforme d''annotation est très ergonomique et réactive.', text2=NULL WHERE id=1;
UPDATE text_pair SET text1='Le modèle a généré des prédictions complètement erronées sur les données de test.', text2=NULL WHERE id=2;
UPDATE text_pair SET text1='Le temps d''inférence de cette architecture réseau est particulièrement impressionnant.', text2=NULL WHERE id=3;
UPDATE text_pair SET text1='L''application backend plante systématiquement lors de l''export des résultats.', text2=NULL WHERE id=4;
UPDATE text_pair SET text1='Le script d''automatisation des déploiements a parfaitement fonctionné.', text2=NULL WHERE id=5;
UPDATE text_pair SET text1='La documentation de l''API REST est confuse et manque d''exemples concrets.', text2=NULL WHERE id=6;
UPDATE text_pair SET text1='Une excellente solution technique pour gérer l''apprentissage supervisé.', text2=NULL WHERE id=7;
UPDATE text_pair SET text1='Le calcul du coefficient de Cohen''s Kappa est beaucoup trop lent.', text2=NULL WHERE id=8;
UPDATE text_pair SET text1='La détection des spammeurs a considérablement amélioré la qualité globale du dataset.', text2=NULL WHERE id=9;
UPDATE text_pair SET text1='Je n''arrive toujours pas à importer les fichiers JSON dans la base de données.', text2=NULL WHERE id=10;
UPDATE text_pair SET text1='Le réseau de neurones converge rapidement vers la solution.', text2='Le modèle Deep Learning apprend très vite.' WHERE id=11;
UPDATE text_pair SET text1='L''erreur quadratique moyenne du modèle est très élevée.', text2='La précision globale du système de classification est excellente.' WHERE id=12;
UPDATE text_pair SET text1='L''algorithme de clustering a bien groupé les données.', text2='Les données d''entrée ont été segmentées par l''algorithme.' WHERE id=13;
UPDATE text_pair SET text1='Le script Python gère tout le preprocessing des données.', text2='La base MariaDB stocke efficacement les logs d''entraînement.' WHERE id=14;
UPDATE text_pair SET text1='L''entraînement a été effectué en utilisant un GPU.', text2='Le modèle a été entraîné grâce à l''accélération matérielle.' WHERE id=15;
UPDATE text_pair SET text1='L''API REST renvoie systématiquement une erreur 404.', text2='Le serveur n''a pas pu trouver la ressource demandée par le client.' WHERE id=16;
UPDATE text_pair SET text1='Le dataset brut contient de nombreuses valeurs nulles.', text2='Les données textuelles d''entrée sont incomplètes.' WHERE id=17;
UPDATE text_pair SET text1='L''interface utilisateur a été configurée en mode sombre.', text2='Le backend de l''application tourne sous le framework Spring Boot.' WHERE id=18;
UPDATE text_pair SET text1='Le taux d''apprentissage de l''optimiseur a été réduit.', text2='Le learning rate a été diminué pour la phase de test.' WHERE id=19;
UPDATE text_pair SET text1='La matrice de confusion montre d''excellents résultats.', text2='Le frontend de l''application a été développé avec Thymeleaf.' WHERE id=20;
UPDATE text_pair SET text1='Le data engineer a écrit un script pour automatiser la pipeline d''approvisionnement.', text2='Un programme informatique a été créé par l''ingénieur.' WHERE id=21;
UPDATE text_pair SET text1='L''application backend est hébergée exclusivement sur un serveur Linux.', text2='L''application est en cours d''exécution sous un environnement Windows.' WHERE id=22;
UPDATE text_pair SET text1='L''administrateur a supprimé définitivement le compte de l''annotateur numéro cinq.', text2='L''annotateur numéro cinq n''a plus aucun accès à la plateforme web.' WHERE id=23;
UPDATE text_pair SET text1='Le modèle de classification a atteint une précision de 95% sur le set de validation.', text2='Le modèle de classification a été testé durant la journée d''hier.' WHERE id=24;
UPDATE text_pair SET text1='Tous les utilisateurs doivent obligatoirement s''authentifier via Spring Security.', text2='Certains utilisateurs peuvent accéder aux données sensibles sans mot de passe.' WHERE id=25;
UPDATE text_pair SET text1='Le dataset importé comporte exactement 100 000 exemples textuels bruts.', text2='Le dataset importé est destiné à être utilisé pour des tâches de NLP.' WHERE id=26;
UPDATE text_pair SET text1='L''entraînement du modèle d''analyse de sentiment prend trois heures complètes.', text2='Le processus d''apprentissage automatique dure exactement 180 minutes.' WHERE id=27;
UPDATE text_pair SET text1='La base de données relationnelle MariaDB a subi un crash critique.', text2='Le serveur hébergeant la base de données est actuellement hors ligne.' WHERE id=28;
UPDATE text_pair SET text1='Les résultats finaux de l''annotation sont exportés au format CSV standard.', text2='L''application web offre la possibilité d''exporter des données structurées.' WHERE id=29;
UPDATE text_pair SET text1='L''annotateur a assigné la classe positive à ce texte spécifique.', text2='Le texte spécifique en question a été catégoriquement rejeté par l''annotateur.' WHERE id=30;