spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 55MB
  datasource:
    url: jdbc:mariadb://localhost:3306/annotation_db
    username: ${DB_USER:annotation}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    root: INFO
    com.annotation: DEBUG
    org.springframework.security: DEBUG
